#!/usr/bin/env python
__author__ = 'schlitzer'

import uvicorn

from dlm_engine.main import app
from dlm_engine.main import settings


if __name__ == '__main__':
    uvicorn.run(app, host=settings.app.host, port=settings.app.port)
